### ISSUE TITLE
Cargo install installs .crates.toml and .crates2.json ?

### ISSUE THREAD

**Issue by jedahan** [jooooscha/terminal-yt-old#6]
Are these files necessary? Is there a way to remove them so I can use cargo install?

**Comment by jooooscha** [comment]
Could you elaborate your problem?
I can install the program after a `git clone` with `cargo install --path <path>`.

**Comment by jedahan** [comment]
Right but if you look at what files cargo install installs, it includes weird hidden files.

try `mkdir fakeroot; cargo install --path . --root fakeroot; ls -al fakeroot`

I figured out the issue, i had to add `--no-track` to `cargo install`. Might be worth updating the readme to include --no-track.

**Comment by jedahan** [comment]
Either way I think the issue is me, not the project.
