### ISSUE TITLE
Failed to compile,  "error: linking with `cc` failed: exit code: 1"

### ISSUE THREAD

**Issue by Pessimystical** [jooooscha/terminal-yt-old#8]
Im trying to compile the source, however something is going wrong and im not sure what. ive tried several times with both the cargo build and cargo build with location commands, same result. also as both a normal user and sudo, same result. Ive created a pastebin for the log, hope this helps.

https://pastebin.com/2EceNQ53

**Comment by jooooscha** [comment]
This does look like you'r missing some libraries. The currently newest commit does compile without problems for me.
